apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    spec:
      initContainers:
        - name: setperms
          image: alpinelinux/darkhttpd
          volumeMounts:
            - name: data
              mountPath: /data
          command:
            - sh
            - -c
            - "chown -R 1000:1000 /data"
          securityContext:
            runAsUser: 0
      containers:
        - name: darkhttpd
          image: alpinelinux/darkhttpd
          volumeMounts:
            - name: data
              mountPath: /data
          containerPorts:
            - name: http
              protocol: TCP
              containerPort: 8080
          securityContext:
            runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: example-data-claim
